In Memory App
GitaVazdike/flight-planner pull request #1
Opened 2022-04-28 21:53 UTC by GitaVazdike

2022-04-29 13:13 UTC, NilsKula requested changes
objects mapes nosukums īsti nepatīk, varētu drīzak būt kaut kāds api vai model varbūt

overall labi :+1:

2022-04-29 13:13 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/controllers/AdminController.java
> +    @PutMapping("/flights")
atkārtojas `/flights`, tad jau ar var uz requstMapping pārnest

2022-04-29 13:13 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/repository/FlightRepository.java
> +        Flight flightFound = null;
šo visu noteikti var smuki pārveidot uz `.stream()`

2022-04-29 13:13 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/repository/FlightRepository.java
> +        for (Flight flight : listOfFlights) {
streams in general labāk izmantot

2022-04-29 13:13 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/repository/FlightRepository.java
> +            if (flight.getFrom().getCountry().toUpperCase().contains(formattedSearchString)
un šo pārbaudi varētu pārnest uz flight klasi labāk `flight.matches(formattedSearchString)` piemēram

2022-04-29 13:13 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/repository/FlightRepository.java
> +        for (Flight flight : listOfFlights) {
te arī :smile:

2022-04-29 13:13 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/repository/FlightRepository.java
> +            String flightDepartureDateToString = flight.getDepartureTime().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
labāk pārveidot searchRequest uz `LocalDate` būs vieglāk pēctam manipulēt lai veidotu papildus sarežģītākus meklējumus

2022-04-29 13:13 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/repository/FlightRepository.java
> +        return addFlightRequest.getFrom().getAirport().trim().equalsIgnoreCase(addFlightRequest.getTo().getAirport().trim())
šķiet jau ka pietiek tik ar airport salīdzināšanu, tas ir unique? (nezinu varbūt uzdevuma noteikumos savadāk bija teikts :smile: ) kā arī šo varētu kā paligmetodi uz airport class

2022-05-04 00:02 UTC, GitaVazdike commented on src/main/java/io/codelex/flightplanner/controllers/AdminController.java
> +    @PutMapping("/flights")
Nesaprotu, kā šo palaidu garām... :D

2022-05-04 00:02 UTC, GitaVazdike commented on src/main/java/io/codelex/flightplanner/repository/FlightRepository.java
> +        Flight flightFound = null;
Izlabots.

2022-05-04 00:02 UTC, GitaVazdike commented on src/main/java/io/codelex/flightplanner/repository/FlightRepository.java
> +        for (Flight flight : listOfFlights) {
Izlabots.

2022-05-04 00:03 UTC, GitaVazdike commented on src/main/java/io/codelex/flightplanner/repository/FlightRepository.java
> +            if (flight.getFrom().getCountry().toUpperCase().contains(formattedSearchString)
Izlabots.

2022-05-04 00:03 UTC, GitaVazdike commented on src/main/java/io/codelex/flightplanner/repository/FlightRepository.java
> +        for (Flight flight : listOfFlights) {
Izlabots.

2022-05-04 00:03 UTC, GitaVazdike commented on src/main/java/io/codelex/flightplanner/repository/FlightRepository.java
> +            String flightDepartureDateToString = flight.getDepartureTime().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
Izlabots.

2022-05-04 00:11 UTC, GitaVazdike commented on src/main/java/io/codelex/flightplanner/repository/FlightRepository.java
> +        return addFlightRequest.getFrom().getAirport().trim().equalsIgnoreCase(addFlightRequest.getTo().getAirport().trim())
Pārcēlu uz Airport klasi.
Vienā testā gan pārvadātāji, gan pilsētu un valstu nosaukumi dažādos testa keisos tiek padoti gan ar lielajiem,  gan mazajiem burtiem, citviet - ar atstarpēm, tāpēc izveidoju šādu metodi.

2022-05-04 11:52 UTC, NilsKula approved these changes
👍

2022-05-05 08:09 UTC, merged